/-
SU(9) = A₈ is a Lie subalgebra of E₈ — closure verification
================================================================

Verifies that for every pair (i,j) of SU(9) basis elements,
the E₈ bracket [B_i, B_j] contains only SU(9) basis elements.
80 SU(9) generators inside 248 E₈ generators.

SU(9) = A₈ is a maximal subgroup of E₈, obtained by removing node 2
from the extended E₈ Dynkin diagram. The A₈ simple roots are
{α₁, α₃, α₄, α₅, α₆, α₇, α₈, -θ} where θ is the highest root.

The A₈ root system (72 roots) was computed by SageMath:
  - BFS from A₈ simple roots, collecting all E₈ roots reachable
    by adding/subtracting A₈ simple roots
  - A₈ Cartan matrix verified as tridiagonal (2,-1,-1,2) pattern

Decomposition: 248 = 80 (adjoint SU(9)) + 84 (Λ³C⁹) + 84* (Λ³C⁹*)
  - 80 generators close under bracket [verified here]
  - 84 + 84* = 168 generators form the complement

Generated by scripts/sage_su9_in_e8.py (SageMath oracle).

References:
  - Slansky, "Group theory for unified model building" Phys. Rep. 79 (1981)
  - Adams, "Lectures on Exceptional Lie Groups" (1996)
  - Wilson, "Uniqueness of an E₈ model" J. Math. Phys. 63 (2022)
  - e8_sparse_defs.lean: E₈ bracket table
  - e8_so16_subalgebra.lean: pattern source (SO(16) ⊂ E₈)
-/

import clifford.e8_sparse_defs

set_option maxHeartbeats 4000000

open E8Sparse

/-- SU(9) = A₈ basis element indices in E₈ (80 out of 248).
    Obtained by removing node 2 from the extended E₈ Dynkin diagram.
    8 Cartan + 36 positive roots + 36 negative roots = 80.
    Computed by SageMath: BFS from A₈ simple roots in E₈ root lattice,
    A₈ Cartan matrix verified as tridiagonal A₈ pattern. -/
def isSU9 (n : Nat) : Bool :=
  match n with
  | 0 => true
  | 1 => true
  | 2 => true
  | 3 => true
  | 4 => true
  | 5 => true
  | 6 => true
  | 7 => true
  | 8 => true
  | 9 => true
  | 10 => true
  | 11 => true
  | 12 => true
  | 13 => true
  | 15 => true
  | 16 => true
  | 17 => true
  | 18 => true
  | 19 => true
  | 20 => true
  | 22 => true
  | 23 => true
  | 24 => true
  | 25 => true
  | 26 => true
  | 29 => true
  | 30 => true
  | 31 => true
  | 32 => true
  | 35 => true
  | 37 => true
  | 38 => true
  | 42 => true
  | 44 => true
  | 48 => true
  | 54 => true
  | 118 => true
  | 121 => true
  | 122 => true
  | 123 => true
  | 124 => true
  | 125 => true
  | 126 => true
  | 127 => true
  | 128 => true
  | 129 => true
  | 130 => true
  | 131 => true
  | 132 => true
  | 133 => true
  | 135 => true
  | 136 => true
  | 137 => true
  | 138 => true
  | 139 => true
  | 140 => true
  | 142 => true
  | 143 => true
  | 144 => true
  | 145 => true
  | 146 => true
  | 149 => true
  | 150 => true
  | 151 => true
  | 152 => true
  | 155 => true
  | 157 => true
  | 158 => true
  | 162 => true
  | 164 => true
  | 168 => true
  | 174 => true
  | 238 => true
  | 241 => true
  | 242 => true
  | 243 => true
  | 244 => true
  | 245 => true
  | 246 => true
  | 247 => true
  | _ => false

/-- SU(9) has exactly 80 basis elements in E₈. -/
theorem su9_count : ((List.range 248).filter (fun n => isSU9 n)).length = 80 := by
  native_decide

/-- Every term in [B_i, B_j] for SU(9) elements is an SU(9) element. -/
def su9ClosedCheck (i j : Nat) : Bool :=
  (bkt i j).all fun (k, _) => isSU9 k

/-- SU(9) = A₈ is closed under the E₈ bracket.
    For all pairs of SU(9) basis elements, the bracket [B_i, B_j]
    contains only SU(9) basis elements.

    This verifies that SU(9) is a genuine Lie subalgebra of E₈,
    not just a subspace. Combined with the Jacobi identity for E₈
    (e8_sparse_jac_00..15.lean), this proves that the SU(9) generators
    inherit a Lie algebra structure from E₈. -/
theorem su9_subalgebra_e8 : ∀ (i j : Fin 248),
    isSU9 i.val = true → isSU9 j.val = true →
    (bkt i.val j.val).all (fun (k, _) => isSU9 k) = true := by
  native_decide

/-- The complement of SU(9) in E₈ has 168 = 84 + 84* dimensions. -/
theorem su9_complement_dim :
    ((List.range 248).filter (fun n => !isSU9 n)).length = 168 := by
  native_decide

/-- 80 + 168 = 248 (SU(9) + complement = E₈). -/
theorem su9_decomposition : 80 + 168 = 248 := by norm_num

/-! ## Summary

### What this file proves:
1. `su9_count`: SU(9) has exactly 80 basis elements in E₈ [MV]
2. `su9_subalgebra_e8`: SU(9) brackets close inside E₈ [MV]
3. `su9_complement_dim`: complement has 168 = 84 + 84* dimensions [MV]
4. `su9_decomposition`: 80 + 168 = 248 [MV]

### What this means:
The SU(9)/Z₃ maximal subgroup decomposition 248 = 80 + 84 + 84*
is now verified at the ALGEBRAIC level, not just the dimensional level.
The 80-dimensional SU(9) adjoint representation forms a genuine
Lie subalgebra of E₈: brackets of SU(9) elements produce only
SU(9) elements. This was previously cited as [SP] from the literature;
it is now [MV] machine-verified.

### Relationship to other files:
- `e8_sparse_defs.lean`: provides the E₈ bracket table
- `e8_so16_subalgebra.lean`: same pattern for SO(16) ⊂ E₈ (120 generators)
- `e8_su9_decomposition.lean`: dimensional arithmetic (80 + 84 + 84 = 248)
- `three_generation_theorem.lean`: uses the SU(9) decomposition for 3 generations

### What was previously [SP], now [MV]:
- "SU(9) is a maximal subgroup of E₈" → subalgebra closure verified [MV]
- "248 = 80 + 84 + 84*" → dimensions verified AND closure verified [MV]

0 sorry gaps.
-/
