/-
UFT Formal Verification - SO(14) Type Bridge: Flat → Matrix
=============================================================

CERTIFIED LieHom: SO14 →ₗ⁅ℝ⁆ SO14M

This file constructs a LieHom from the flat 91-field SO14 type
(so14_grand.lean) to the mathlib matrix SO14M type (so16_matrix.lean).

SO14M is `LieAlgebra.Orthogonal.so (Fin 14) ℝ`, the Lie subalgebra of
14×14 antisymmetric real matrices. The bracket is the matrix commutator:
  [A, B] = A * B - B * A

The map sends each generator field l_{ij} to the antisymmetric basis
matrix E_{i-1,j-1} - E_{j-1,i-1}, producing a 14×14 matrix whose
upper-triangular entries are exactly the SO14 fields.

This bridge resolves the type gap between the flat algebraic construction
(SO14 with explicit structure constants) and the matrix formulation
(SO14M with inherited mathlib LieAlgebra instance).

Generated by scripts/so14_bridge_gen.py.

References:
  - so14_grand.lean: SO14 type with 91 generators, LieAlgebra ℝ instance
  - so16_matrix.lean: SO14M = LieAlgebra.Orthogonal.so (Fin 14) ℝ
  - su5c_so10_liehom.lean: LieHom pattern source
-/

import clifford.so14_grand
import clifford.so16_matrix

open Matrix LieAlgebra.Orthogonal

/-! ## Part 1: The Map SO14 → Matrix (Fin 14) (Fin 14) ℝ

Each flat field l_{ij} maps to the antisymmetric matrix with +1 at
position (i-1, j-1) and -1 at position (j-1, i-1).

Defined entry-by-entry for clean simp reduction. -/

/-- Map from flat SO14 (91 generators) to 14×14 real matrix.
    Upper triangle: x.l_{i+1,j+1} for i < j.
    Lower triangle: -x.l_{j+1,i+1} for i > j.
    Diagonal: 0.
    Generated by scripts/so14_bridge_gen.py. -/
def so14_to_mat (x : SO14) : Matrix (Fin 14) (Fin 14) ℝ := fun i j =>
  match i.val, j.val with
  | 0, 1 => x.l12
  | 0, 2 => x.l13
  | 0, 3 => x.l14
  | 0, 4 => x.l15
  | 0, 5 => x.l16
  | 0, 6 => x.l17
  | 0, 7 => x.l18
  | 0, 8 => x.l19
  | 0, 9 => x.l1a
  | 0, 10 => x.l1b
  | 0, 11 => x.l1c
  | 0, 12 => x.l1d
  | 0, 13 => x.l1e
  | 1, 2 => x.l23
  | 1, 3 => x.l24
  | 1, 4 => x.l25
  | 1, 5 => x.l26
  | 1, 6 => x.l27
  | 1, 7 => x.l28
  | 1, 8 => x.l29
  | 1, 9 => x.l2a
  | 1, 10 => x.l2b
  | 1, 11 => x.l2c
  | 1, 12 => x.l2d
  | 1, 13 => x.l2e
  | 2, 3 => x.l34
  | 2, 4 => x.l35
  | 2, 5 => x.l36
  | 2, 6 => x.l37
  | 2, 7 => x.l38
  | 2, 8 => x.l39
  | 2, 9 => x.l3a
  | 2, 10 => x.l3b
  | 2, 11 => x.l3c
  | 2, 12 => x.l3d
  | 2, 13 => x.l3e
  | 3, 4 => x.l45
  | 3, 5 => x.l46
  | 3, 6 => x.l47
  | 3, 7 => x.l48
  | 3, 8 => x.l49
  | 3, 9 => x.l4a
  | 3, 10 => x.l4b
  | 3, 11 => x.l4c
  | 3, 12 => x.l4d
  | 3, 13 => x.l4e
  | 4, 5 => x.l56
  | 4, 6 => x.l57
  | 4, 7 => x.l58
  | 4, 8 => x.l59
  | 4, 9 => x.l5a
  | 4, 10 => x.l5b
  | 4, 11 => x.l5c
  | 4, 12 => x.l5d
  | 4, 13 => x.l5e
  | 5, 6 => x.l67
  | 5, 7 => x.l68
  | 5, 8 => x.l69
  | 5, 9 => x.l6a
  | 5, 10 => x.l6b
  | 5, 11 => x.l6c
  | 5, 12 => x.l6d
  | 5, 13 => x.l6e
  | 6, 7 => x.l78
  | 6, 8 => x.l79
  | 6, 9 => x.l7a
  | 6, 10 => x.l7b
  | 6, 11 => x.l7c
  | 6, 12 => x.l7d
  | 6, 13 => x.l7e
  | 7, 8 => x.l89
  | 7, 9 => x.l8a
  | 7, 10 => x.l8b
  | 7, 11 => x.l8c
  | 7, 12 => x.l8d
  | 7, 13 => x.l8e
  | 8, 9 => x.l9a
  | 8, 10 => x.l9b
  | 8, 11 => x.l9c
  | 8, 12 => x.l9d
  | 8, 13 => x.l9e
  | 9, 10 => x.lab
  | 9, 11 => x.lac
  | 9, 12 => x.lad
  | 9, 13 => x.lae
  | 10, 11 => x.lbc
  | 10, 12 => x.lbd
  | 10, 13 => x.lbe
  | 11, 12 => x.lcd
  | 11, 13 => x.lce
  | 12, 13 => x.lde
  | 1, 0 => -x.l12
  | 2, 0 => -x.l13
  | 3, 0 => -x.l14
  | 4, 0 => -x.l15
  | 5, 0 => -x.l16
  | 6, 0 => -x.l17
  | 7, 0 => -x.l18
  | 8, 0 => -x.l19
  | 9, 0 => -x.l1a
  | 10, 0 => -x.l1b
  | 11, 0 => -x.l1c
  | 12, 0 => -x.l1d
  | 13, 0 => -x.l1e
  | 2, 1 => -x.l23
  | 3, 1 => -x.l24
  | 4, 1 => -x.l25
  | 5, 1 => -x.l26
  | 6, 1 => -x.l27
  | 7, 1 => -x.l28
  | 8, 1 => -x.l29
  | 9, 1 => -x.l2a
  | 10, 1 => -x.l2b
  | 11, 1 => -x.l2c
  | 12, 1 => -x.l2d
  | 13, 1 => -x.l2e
  | 3, 2 => -x.l34
  | 4, 2 => -x.l35
  | 5, 2 => -x.l36
  | 6, 2 => -x.l37
  | 7, 2 => -x.l38
  | 8, 2 => -x.l39
  | 9, 2 => -x.l3a
  | 10, 2 => -x.l3b
  | 11, 2 => -x.l3c
  | 12, 2 => -x.l3d
  | 13, 2 => -x.l3e
  | 4, 3 => -x.l45
  | 5, 3 => -x.l46
  | 6, 3 => -x.l47
  | 7, 3 => -x.l48
  | 8, 3 => -x.l49
  | 9, 3 => -x.l4a
  | 10, 3 => -x.l4b
  | 11, 3 => -x.l4c
  | 12, 3 => -x.l4d
  | 13, 3 => -x.l4e
  | 5, 4 => -x.l56
  | 6, 4 => -x.l57
  | 7, 4 => -x.l58
  | 8, 4 => -x.l59
  | 9, 4 => -x.l5a
  | 10, 4 => -x.l5b
  | 11, 4 => -x.l5c
  | 12, 4 => -x.l5d
  | 13, 4 => -x.l5e
  | 6, 5 => -x.l67
  | 7, 5 => -x.l68
  | 8, 5 => -x.l69
  | 9, 5 => -x.l6a
  | 10, 5 => -x.l6b
  | 11, 5 => -x.l6c
  | 12, 5 => -x.l6d
  | 13, 5 => -x.l6e
  | 7, 6 => -x.l78
  | 8, 6 => -x.l79
  | 9, 6 => -x.l7a
  | 10, 6 => -x.l7b
  | 11, 6 => -x.l7c
  | 12, 6 => -x.l7d
  | 13, 6 => -x.l7e
  | 8, 7 => -x.l89
  | 9, 7 => -x.l8a
  | 10, 7 => -x.l8b
  | 11, 7 => -x.l8c
  | 12, 7 => -x.l8d
  | 13, 7 => -x.l8e
  | 9, 8 => -x.l9a
  | 10, 8 => -x.l9b
  | 11, 8 => -x.l9c
  | 12, 8 => -x.l9d
  | 13, 8 => -x.l9e
  | 10, 9 => -x.lab
  | 11, 9 => -x.lac
  | 12, 9 => -x.lad
  | 13, 9 => -x.lae
  | 11, 10 => -x.lbc
  | 12, 10 => -x.lbd
  | 13, 10 => -x.lbe
  | 12, 11 => -x.lcd
  | 13, 11 => -x.lce
  | 13, 12 => -x.lde
  | _, _ => 0

/-! ## Part 2: Skew-Symmetry and SO14M Membership -/

set_option maxHeartbeats 4000000 in
/-- The output matrix is skew-symmetric: (so14_to_mat x)ᵀ = -(so14_to_mat x). -/
theorem so14_to_mat_skew (x : SO14) : (so14_to_mat x)ᵀ = -(so14_to_mat x) := by
  ext i j
  simp only [Matrix.transpose_apply, Matrix.neg_apply]
  fin_cases i <;> fin_cases j <;> simp [so14_to_mat]

/-- The output matrix is in SO14M (the so(14) LieSubalgebra of antisymmetric matrices). -/
theorem so14_to_mat_mem (x : SO14) : so14_to_mat x ∈ SO14M := by
  rw [LieAlgebra.Orthogonal.mem_so]
  exact so14_to_mat_skew x

/-- Lift the map to target SO14M (subtype of antisymmetric matrices). -/
def so14_to_SO14M (x : SO14) : SO14M :=
  ⟨so14_to_mat x, so14_to_mat_mem x⟩

/-! ## Part 3: Linearity -/

set_option maxHeartbeats 4000000 in
/-- The map preserves addition. -/
theorem so14_to_SO14M_add (a b : SO14) :
    so14_to_SO14M (a + b) = so14_to_SO14M a + so14_to_SO14M b := by
  apply Subtype.ext
  ext i j
  simp only [so14_to_SO14M, AddMemClass.coe_add, Matrix.add_apply]
  fin_cases i <;> fin_cases j <;> simp [so14_to_mat, SO14.add, SO14.add_def] <;> ring

set_option maxHeartbeats 4000000 in
/-- The map preserves scalar multiplication. -/
theorem so14_to_SO14M_smul (r : ℝ) (a : SO14) :
    so14_to_SO14M (r • a) = r • so14_to_SO14M a := by
  apply Subtype.ext
  ext i j
  simp only [so14_to_SO14M, SetLike.val_smul, Matrix.smul_apply, smul_eq_mul]
  fin_cases i <;> fin_cases j <;> simp [so14_to_mat, SO14.smul, SO14.smul_def']

/-! ## Part 4: Bracket Preservation

The main theorem: so14_to_SO14M preserves the Lie bracket.

LHS: so14_to_mat (comm x y) — the flat bracket mapped to a matrix.
RHS: so14_to_mat x * so14_to_mat y - so14_to_mat y * so14_to_mat x — the matrix commutator.

Both sides are degree-2 polynomials in the 182 input variables (91 from x, 91 from y).
After fin_cases on matrix indices, each of the 196 goals is verified by ring.

The proof is split into 14 row lemmas for manageable compilation. -/

-- Helper: expand Finset.sum over Fin 14
-- This lets simp reduce matrix multiplication entries.
@[simp] theorem sum_fin14 {M : Type*} [AddCommMonoid M] (f : Fin 14 → M) :
    ∑ i : Fin 14, f i = f 0 + f 1 + f 2 + f 3 + f 4 + f 5 + f 6 + f 7 +
                         f 8 + f 9 + f 10 + f 11 + f 12 + f 13 := by
  simp only [Fin.sum_univ_succ, Fin.sum_univ_zero]
  abel

set_option maxHeartbeats 64000000 in
/-- Bracket preservation, row 0. -/
theorem so14_bridge_lie_row0 (x y : SO14) (j : Fin 14) :
    so14_to_mat ⁅x, y⁆ 0 j =
    (so14_to_mat x * so14_to_mat y - so14_to_mat y * so14_to_mat x) 0 j := by
  simp only [SO14.bracket_def', Matrix.sub_apply, Matrix.mul_apply, sum_fin14]
  fin_cases j <;> simp [so14_to_mat, SO14.comm] <;> ring

set_option maxHeartbeats 64000000 in
/-- Bracket preservation, row 1. -/
theorem so14_bridge_lie_row1 (x y : SO14) (j : Fin 14) :
    so14_to_mat ⁅x, y⁆ 1 j =
    (so14_to_mat x * so14_to_mat y - so14_to_mat y * so14_to_mat x) 1 j := by
  simp only [SO14.bracket_def', Matrix.sub_apply, Matrix.mul_apply, sum_fin14]
  fin_cases j <;> simp [so14_to_mat, SO14.comm] <;> ring

set_option maxHeartbeats 64000000 in
/-- Bracket preservation, row 2. -/
theorem so14_bridge_lie_row2 (x y : SO14) (j : Fin 14) :
    so14_to_mat ⁅x, y⁆ 2 j =
    (so14_to_mat x * so14_to_mat y - so14_to_mat y * so14_to_mat x) 2 j := by
  simp only [SO14.bracket_def', Matrix.sub_apply, Matrix.mul_apply, sum_fin14]
  fin_cases j <;> simp [so14_to_mat, SO14.comm] <;> ring

set_option maxHeartbeats 64000000 in
/-- Bracket preservation, row 3. -/
theorem so14_bridge_lie_row3 (x y : SO14) (j : Fin 14) :
    so14_to_mat ⁅x, y⁆ 3 j =
    (so14_to_mat x * so14_to_mat y - so14_to_mat y * so14_to_mat x) 3 j := by
  simp only [SO14.bracket_def', Matrix.sub_apply, Matrix.mul_apply, sum_fin14]
  fin_cases j <;> simp [so14_to_mat, SO14.comm] <;> ring

set_option maxHeartbeats 64000000 in
/-- Bracket preservation, row 4. -/
theorem so14_bridge_lie_row4 (x y : SO14) (j : Fin 14) :
    so14_to_mat ⁅x, y⁆ 4 j =
    (so14_to_mat x * so14_to_mat y - so14_to_mat y * so14_to_mat x) 4 j := by
  simp only [SO14.bracket_def', Matrix.sub_apply, Matrix.mul_apply, sum_fin14]
  fin_cases j <;> simp [so14_to_mat, SO14.comm] <;> ring

set_option maxHeartbeats 64000000 in
/-- Bracket preservation, row 5. -/
theorem so14_bridge_lie_row5 (x y : SO14) (j : Fin 14) :
    so14_to_mat ⁅x, y⁆ 5 j =
    (so14_to_mat x * so14_to_mat y - so14_to_mat y * so14_to_mat x) 5 j := by
  simp only [SO14.bracket_def', Matrix.sub_apply, Matrix.mul_apply, sum_fin14]
  fin_cases j <;> simp [so14_to_mat, SO14.comm] <;> ring

set_option maxHeartbeats 64000000 in
/-- Bracket preservation, row 6. -/
theorem so14_bridge_lie_row6 (x y : SO14) (j : Fin 14) :
    so14_to_mat ⁅x, y⁆ 6 j =
    (so14_to_mat x * so14_to_mat y - so14_to_mat y * so14_to_mat x) 6 j := by
  simp only [SO14.bracket_def', Matrix.sub_apply, Matrix.mul_apply, sum_fin14]
  fin_cases j <;> simp [so14_to_mat, SO14.comm] <;> ring

set_option maxHeartbeats 64000000 in
/-- Bracket preservation, row 7. -/
theorem so14_bridge_lie_row7 (x y : SO14) (j : Fin 14) :
    so14_to_mat ⁅x, y⁆ 7 j =
    (so14_to_mat x * so14_to_mat y - so14_to_mat y * so14_to_mat x) 7 j := by
  simp only [SO14.bracket_def', Matrix.sub_apply, Matrix.mul_apply, sum_fin14]
  fin_cases j <;> simp [so14_to_mat, SO14.comm] <;> ring

set_option maxHeartbeats 64000000 in
/-- Bracket preservation, row 8. -/
theorem so14_bridge_lie_row8 (x y : SO14) (j : Fin 14) :
    so14_to_mat ⁅x, y⁆ 8 j =
    (so14_to_mat x * so14_to_mat y - so14_to_mat y * so14_to_mat x) 8 j := by
  simp only [SO14.bracket_def', Matrix.sub_apply, Matrix.mul_apply, sum_fin14]
  fin_cases j <;> simp [so14_to_mat, SO14.comm] <;> ring

set_option maxHeartbeats 64000000 in
/-- Bracket preservation, row 9. -/
theorem so14_bridge_lie_row9 (x y : SO14) (j : Fin 14) :
    so14_to_mat ⁅x, y⁆ 9 j =
    (so14_to_mat x * so14_to_mat y - so14_to_mat y * so14_to_mat x) 9 j := by
  simp only [SO14.bracket_def', Matrix.sub_apply, Matrix.mul_apply, sum_fin14]
  fin_cases j <;> simp [so14_to_mat, SO14.comm] <;> ring

set_option maxHeartbeats 64000000 in
/-- Bracket preservation, row 10. -/
theorem so14_bridge_lie_row10 (x y : SO14) (j : Fin 14) :
    so14_to_mat ⁅x, y⁆ 10 j =
    (so14_to_mat x * so14_to_mat y - so14_to_mat y * so14_to_mat x) 10 j := by
  simp only [SO14.bracket_def', Matrix.sub_apply, Matrix.mul_apply, sum_fin14]
  fin_cases j <;> simp [so14_to_mat, SO14.comm] <;> ring

set_option maxHeartbeats 64000000 in
/-- Bracket preservation, row 11. -/
theorem so14_bridge_lie_row11 (x y : SO14) (j : Fin 14) :
    so14_to_mat ⁅x, y⁆ 11 j =
    (so14_to_mat x * so14_to_mat y - so14_to_mat y * so14_to_mat x) 11 j := by
  simp only [SO14.bracket_def', Matrix.sub_apply, Matrix.mul_apply, sum_fin14]
  fin_cases j <;> simp [so14_to_mat, SO14.comm] <;> ring

set_option maxHeartbeats 64000000 in
/-- Bracket preservation, row 12. -/
theorem so14_bridge_lie_row12 (x y : SO14) (j : Fin 14) :
    so14_to_mat ⁅x, y⁆ 12 j =
    (so14_to_mat x * so14_to_mat y - so14_to_mat y * so14_to_mat x) 12 j := by
  simp only [SO14.bracket_def', Matrix.sub_apply, Matrix.mul_apply, sum_fin14]
  fin_cases j <;> simp [so14_to_mat, SO14.comm] <;> ring

set_option maxHeartbeats 64000000 in
/-- Bracket preservation, row 13. -/
theorem so14_bridge_lie_row13 (x y : SO14) (j : Fin 14) :
    so14_to_mat ⁅x, y⁆ 13 j =
    (so14_to_mat x * so14_to_mat y - so14_to_mat y * so14_to_mat x) 13 j := by
  simp only [SO14.bracket_def', Matrix.sub_apply, Matrix.mul_apply, sum_fin14]
  fin_cases j <;> simp [so14_to_mat, SO14.comm] <;> ring

set_option maxHeartbeats 4000000 in
/-- THE HOMOMORPHISM THEOREM: the map preserves the Lie bracket.
    so14_to_SO14M([X,Y]_{so14}) = [so14_to_SO14M(X), so14_to_SO14M(Y)]_{so14m}

    This certifies that the flat SO14 bracket (defined by structure constants)
    and the matrix SO14M bracket (defined by the commutator A*B - B*A) are
    algebraically identical under the type bridge.

    182 input variables × 196 output entries × polynomial ring verification.
    Split into 14 row lemmas for compilation. -/
theorem so14_to_SO14M_lie (x y : SO14) :
    so14_to_SO14M ⁅x, y⁆ = ⁅so14_to_SO14M x, so14_to_SO14M y⁆ := by
  apply Subtype.ext
  simp only [LieSubalgebra.coe_bracket, LieRing.of_associative_ring_bracket, so14_to_SO14M]
  ext i j
  fin_cases i
  · exact so14_bridge_lie_row0 x y j
  · exact so14_bridge_lie_row1 x y j
  · exact so14_bridge_lie_row2 x y j
  · exact so14_bridge_lie_row3 x y j
  · exact so14_bridge_lie_row4 x y j
  · exact so14_bridge_lie_row5 x y j
  · exact so14_bridge_lie_row6 x y j
  · exact so14_bridge_lie_row7 x y j
  · exact so14_bridge_lie_row8 x y j
  · exact so14_bridge_lie_row9 x y j
  · exact so14_bridge_lie_row10 x y j
  · exact so14_bridge_lie_row11 x y j
  · exact so14_bridge_lie_row12 x y j
  · exact so14_bridge_lie_row13 x y j

/-! ## Part 5: The Certified LieHom -/

/-- The certified Lie algebra homomorphism SO14 →ₗ⁅ℝ⁆ SO14M.
    This bridges the flat 91-field type (with explicit structure constants)
    to the mathlib matrix type (with inherited bracket from matrix commutator).

    Combined with the existing morphism chain:
      SU5C →ₗ⁅ℝ⁆ SO10 →ₗ⁅ℝ⁆ SO14 →ₗ⁅ℝ⁆[bridge] SO14M →ₗ⁅ℝ⁆ SO16M

    This connects the verified algebraic chain to mathlib's matrix infrastructure,
    enabling composition with so14m_embed_block : SO14M →ₗ⁅ℝ⁆ SO16Block. -/
def so14_bridge : SO14 →ₗ⁅ℝ⁆ SO14M :=
  { toLinearMap := {
      toFun := so14_to_SO14M
      map_add' := so14_to_SO14M_add
      map_smul' := so14_to_SO14M_smul
    }
    map_lie' := fun {x} {y} => so14_to_SO14M_lie x y }

/-! ## Summary

### What this file proves:
1. `so14_to_mat` : SO14 → Matrix (Fin 14) (Fin 14) ℝ (entry-by-entry map) [Part 1]
2. Skew-symmetry: output is always antisymmetric [Part 2]
3. SO14M membership: output is in so(14) LieSubalgebra [Part 2]
4. Linearity: preserves addition and scalar multiplication [Part 3]
5. Bracket preservation: flat bracket = matrix commutator [Part 4]
6. `so14_bridge` : SO14 →ₗ⁅ℝ⁆ SO14M — certified LieHom [Part 5]

### What this resolves:
The type gap between flat SO14 (with hand-written bracket) and matrix SO14M
(with mathlib-inherited bracket). This is the bridge that connects the
algebraic chain (SU5C → SO10 → SO14) to the matrix chain (SO14M → SO16M).

### Full certified chain (with bridge):
  SU5C →ₗ⁅ℝ⁆ SO10 →ₗ⁅ℝ⁆ SO14 →[so14_bridge]→ SO14M →[so14m_embed_block]→ SO16Block

0 sorry gaps.
-/
