/-
UFT Formal Verification - SU(5) Compact Form (Level 13b)
=========================================================

THE COMPACT FORM su(5) AS A STANDALONE TYPE

This file defines the compact real form su(5) as a 24-dimensional
Lie algebra with certified LieRing and LieAlgebra ℝ instances.

Unlike su5_grand.lean (which defines sl(5,ℝ) in the Chevalley basis,
the split real form), this is the COMPACT real form — the one that
actually embeds in so(10) via the complex structure J.

The 24 generators decompose into:
  4 Cartan:  H_a = L_{a,a+5} - L_{a+1,a+6}    (a = 1,...,4)
  10 Type-R: R_{ab} = L_{ab} + L_{a+5,b+5}      (1 ≤ a < b ≤ 5)
  10 Type-S: S_{ab} = L_{a,b+5} + L_{b,a+5}     (1 ≤ a < b ≤ 5)

Structure constants computed by scripts/su5c_bracket_gen.py from
the so(10) bracket restricted to the su(5) subalgebra.
All 276 independent brackets verified to close. Jacobi verified
numerically for 1000 random triples before Lean compilation.

References:
  - su5_so10_embedding.lean: generator definitions and [G,J]=0 proofs
  - su5_lie_structure.lean: A₄ Cartan matrix verification
  - Georgi, "Lie Algebras in Particle Physics" (1999), Ch. 24
-/

import Mathlib.Data.Real.Basic
import Mathlib.Tactic
import Mathlib.Algebra.Lie.Basic

/-! ## Part 1: The su(5) Compact Form Structure -/

/-- The compact real form su(5), with 24 generators:
    4 Cartan (h), 10 Type-R (real rotations), 10 Type-S (symplectic). -/
@[ext]
structure SU5C where
  h1 : ℝ       -- Cartan H₁ = L_{1,6} - L_{2,7}
  h2 : ℝ       -- Cartan H₂ = L_{2,7} - L_{3,8}
  h3 : ℝ       -- Cartan H₃ = L_{3,8} - L_{4,9}
  h4 : ℝ       -- Cartan H₄ = L_{4,9} - L_{5,10}
  r12 : ℝ      -- R_{12} = L_{1,2} + L_{6,7}
  r13 : ℝ      -- R_{13} = L_{1,3} + L_{6,8}
  r14 : ℝ      -- R_{14} = L_{1,4} + L_{6,9}
  r15 : ℝ      -- R_{15} = L_{1,5} + L_{6,10}
  r23 : ℝ      -- R_{23} = L_{2,3} + L_{7,8}
  r24 : ℝ      -- R_{24} = L_{2,4} + L_{7,9}
  r25 : ℝ      -- R_{25} = L_{2,5} + L_{7,10}
  r34 : ℝ      -- R_{34} = L_{3,4} + L_{8,9}
  r35 : ℝ      -- R_{35} = L_{3,5} + L_{8,10}
  r45 : ℝ      -- R_{45} = L_{4,5} + L_{9,10}
  s12 : ℝ      -- S_{12} = L_{1,7} + L_{2,6}
  s13 : ℝ      -- S_{13} = L_{1,8} + L_{3,6}
  s14 : ℝ      -- S_{14} = L_{1,9} + L_{4,6}
  s15 : ℝ      -- S_{15} = L_{1,10} + L_{5,6}
  s23 : ℝ      -- S_{23} = L_{2,8} + L_{3,7}
  s24 : ℝ      -- S_{24} = L_{2,9} + L_{4,7}
  s25 : ℝ      -- S_{25} = L_{2,10} + L_{5,7}
  s34 : ℝ      -- S_{34} = L_{3,9} + L_{4,8}
  s35 : ℝ      -- S_{35} = L_{3,10} + L_{5,8}
  s45 : ℝ      -- S_{45} = L_{4,10} + L_{5,9}

namespace SU5C

/-! ## Part 2: Basic Operations -/

def zero : SU5C :=
  ⟨0,0,0,0, 0,0,0,0,0,0,0,0,0,0, 0,0,0,0,0,0,0,0,0,0⟩

def neg (x : SU5C) : SU5C :=
  ⟨-x.h1, -x.h2, -x.h3, -x.h4,
   -x.r12, -x.r13, -x.r14, -x.r15, -x.r23, -x.r24, -x.r25, -x.r34, -x.r35, -x.r45,
   -x.s12, -x.s13, -x.s14, -x.s15, -x.s23, -x.s24, -x.s25, -x.s34, -x.s35, -x.s45⟩

def add (x y : SU5C) : SU5C :=
  ⟨x.h1+y.h1, x.h2+y.h2, x.h3+y.h3, x.h4+y.h4,
   x.r12+y.r12, x.r13+y.r13, x.r14+y.r14, x.r15+y.r15,
   x.r23+y.r23, x.r24+y.r24, x.r25+y.r25, x.r34+y.r34, x.r35+y.r35, x.r45+y.r45,
   x.s12+y.s12, x.s13+y.s13, x.s14+y.s14, x.s15+y.s15,
   x.s23+y.s23, x.s24+y.s24, x.s25+y.s25, x.s34+y.s34, x.s35+y.s35, x.s45+y.s45⟩

def smul (r : ℝ) (x : SU5C) : SU5C :=
  ⟨r*x.h1, r*x.h2, r*x.h3, r*x.h4,
   r*x.r12, r*x.r13, r*x.r14, r*x.r15,
   r*x.r23, r*x.r24, r*x.r25, r*x.r34, r*x.r35, r*x.r45,
   r*x.s12, r*x.s13, r*x.s14, r*x.s15,
   r*x.s23, r*x.s24, r*x.s25, r*x.s34, r*x.s35, r*x.s45⟩

instance : Add SU5C := ⟨add⟩
instance : Neg SU5C := ⟨neg⟩
instance : Zero SU5C := ⟨zero⟩

@[simp] lemma add_def (a b : SU5C) : a + b = add a b := rfl
@[simp] lemma neg_def (a : SU5C) : -a = neg a := rfl
@[simp] lemma zero_val : (0 : SU5C) = zero := rfl

/-! ## Part 3: The Lie Bracket

All structure constants computed by scripts/su5c_bracket_gen.py.
The bracket is the restriction of so(10)'s bracket to the 24-dim
su(5) subalgebra. Structure constants are integers in {-2,-1,0,1,2}.

Generated from 276 independent basis pair brackets. -/

/-- The Lie bracket of su(5) in the compact basis.
    Generated by scripts/su5c_bracket_gen.py from the so(10) bracket
    restricted to the su(5) subalgebra (centralizer of J). -/
def comm (X Y : SU5C) : SU5C where
  h1 := 2 * (X.r12 * Y.s12 - X.s12 * Y.r12) + 2 * (X.r13 * Y.s13 - X.s13 * Y.r13) + 2 * (X.r14 * Y.s14 - X.s14 * Y.r14) + 2 * (X.r15 * Y.s15 - X.s15 * Y.r15)
  h2 := 2 * (X.r13 * Y.s13 - X.s13 * Y.r13) + 2 * (X.r14 * Y.s14 - X.s14 * Y.r14) + 2 * (X.r15 * Y.s15 - X.s15 * Y.r15) + 2 * (X.r23 * Y.s23 - X.s23 * Y.r23) + 2 * (X.r24 * Y.s24 - X.s24 * Y.r24) + 2 * (X.r25 * Y.s25 - X.s25 * Y.r25)
  h3 := 2 * (X.r14 * Y.s14 - X.s14 * Y.r14) + 2 * (X.r15 * Y.s15 - X.s15 * Y.r15) + 2 * (X.r24 * Y.s24 - X.s24 * Y.r24) + 2 * (X.r25 * Y.s25 - X.s25 * Y.r25) + 2 * (X.r34 * Y.s34 - X.s34 * Y.r34) + 2 * (X.r35 * Y.s35 - X.s35 * Y.r35)
  h4 := 2 * (X.r15 * Y.s15 - X.s15 * Y.r15) + 2 * (X.r25 * Y.s25 - X.s25 * Y.r25) + 2 * (X.r35 * Y.s35 - X.s35 * Y.r35) + 2 * (X.r45 * Y.s45 - X.s45 * Y.r45)
  r12 := 2 * (X.s12 * Y.h1 - X.h1 * Y.s12) + (X.h2 * Y.s12 - X.s12 * Y.h2) + (X.r23 * Y.r13 - X.r13 * Y.r23) + (X.r24 * Y.r14 - X.r14 * Y.r24) + (X.r25 * Y.r15 - X.r15 * Y.r25) + (X.s23 * Y.s13 - X.s13 * Y.s23) + (X.s24 * Y.s14 - X.s14 * Y.s24) + (X.s25 * Y.s15 - X.s15 * Y.s25)
  r13 := (X.s13 * Y.h1 - X.h1 * Y.s13) + (X.s13 * Y.h2 - X.h2 * Y.s13) + (X.h3 * Y.s13 - X.s13 * Y.h3) + (X.r12 * Y.r23 - X.r23 * Y.r12) + (X.r34 * Y.r14 - X.r14 * Y.r34) + (X.r35 * Y.r15 - X.r15 * Y.r35) + (X.s23 * Y.s12 - X.s12 * Y.s23) + (X.s34 * Y.s14 - X.s14 * Y.s34) + (X.s35 * Y.s15 - X.s15 * Y.s35)
  r14 := (X.s14 * Y.h1 - X.h1 * Y.s14) + (X.s14 * Y.h3 - X.h3 * Y.s14) + (X.h4 * Y.s14 - X.s14 * Y.h4) + (X.r12 * Y.r24 - X.r24 * Y.r12) + (X.r13 * Y.r34 - X.r34 * Y.r13) + (X.r45 * Y.r15 - X.r15 * Y.r45) + (X.s24 * Y.s12 - X.s12 * Y.s24) + (X.s34 * Y.s13 - X.s13 * Y.s34) + (X.s45 * Y.s15 - X.s15 * Y.s45)
  r15 := (X.s15 * Y.h1 - X.h1 * Y.s15) + (X.s15 * Y.h4 - X.h4 * Y.s15) + (X.r12 * Y.r25 - X.r25 * Y.r12) + (X.r13 * Y.r35 - X.r35 * Y.r13) + (X.r14 * Y.r45 - X.r45 * Y.r14) + (X.s25 * Y.s12 - X.s12 * Y.s25) + (X.s35 * Y.s13 - X.s13 * Y.s35) + (X.s45 * Y.s14 - X.s14 * Y.s45)
  r23 := (X.h1 * Y.s23 - X.s23 * Y.h1) + 2 * (X.s23 * Y.h2 - X.h2 * Y.s23) + (X.h3 * Y.s23 - X.s23 * Y.h3) + (X.r13 * Y.r12 - X.r12 * Y.r13) + (X.r34 * Y.r24 - X.r24 * Y.r34) + (X.r35 * Y.r25 - X.r25 * Y.r35) + (X.s13 * Y.s12 - X.s12 * Y.s13) + (X.s34 * Y.s24 - X.s24 * Y.s34) + (X.s35 * Y.s25 - X.s25 * Y.s35)
  r24 := (X.h1 * Y.s24 - X.s24 * Y.h1) + (X.s24 * Y.h2 - X.h2 * Y.s24) + (X.s24 * Y.h3 - X.h3 * Y.s24) + (X.h4 * Y.s24 - X.s24 * Y.h4) + (X.r14 * Y.r12 - X.r12 * Y.r14) + (X.r23 * Y.r34 - X.r34 * Y.r23) + (X.r45 * Y.r25 - X.r25 * Y.r45) + (X.s14 * Y.s12 - X.s12 * Y.s14) + (X.s34 * Y.s23 - X.s23 * Y.s34) + (X.s45 * Y.s25 - X.s25 * Y.s45)
  r25 := (X.h1 * Y.s25 - X.s25 * Y.h1) + (X.s25 * Y.h2 - X.h2 * Y.s25) + (X.s25 * Y.h4 - X.h4 * Y.s25) + (X.r15 * Y.r12 - X.r12 * Y.r15) + (X.r23 * Y.r35 - X.r35 * Y.r23) + (X.r24 * Y.r45 - X.r45 * Y.r24) + (X.s15 * Y.s12 - X.s12 * Y.s15) + (X.s35 * Y.s23 - X.s23 * Y.s35) + (X.s45 * Y.s24 - X.s24 * Y.s45)
  r34 := (X.h2 * Y.s34 - X.s34 * Y.h2) + 2 * (X.s34 * Y.h3 - X.h3 * Y.s34) + (X.h4 * Y.s34 - X.s34 * Y.h4) + (X.r14 * Y.r13 - X.r13 * Y.r14) + (X.r24 * Y.r23 - X.r23 * Y.r24) + (X.r45 * Y.r35 - X.r35 * Y.r45) + (X.s14 * Y.s13 - X.s13 * Y.s14) + (X.s24 * Y.s23 - X.s23 * Y.s24) + (X.s45 * Y.s35 - X.s35 * Y.s45)
  r35 := (X.h2 * Y.s35 - X.s35 * Y.h2) + (X.s35 * Y.h3 - X.h3 * Y.s35) + (X.s35 * Y.h4 - X.h4 * Y.s35) + (X.r15 * Y.r13 - X.r13 * Y.r15) + (X.r25 * Y.r23 - X.r23 * Y.r25) + (X.r34 * Y.r45 - X.r45 * Y.r34) + (X.s15 * Y.s13 - X.s13 * Y.s15) + (X.s25 * Y.s23 - X.s23 * Y.s25) + (X.s45 * Y.s34 - X.s34 * Y.s45)
  r45 := (X.h3 * Y.s45 - X.s45 * Y.h3) + 2 * (X.s45 * Y.h4 - X.h4 * Y.s45) + (X.r15 * Y.r14 - X.r14 * Y.r15) + (X.r25 * Y.r24 - X.r24 * Y.r25) + (X.r35 * Y.r34 - X.r34 * Y.r35) + (X.s15 * Y.s14 - X.s14 * Y.s15) + (X.s25 * Y.s24 - X.s24 * Y.s25) + (X.s35 * Y.s34 - X.s34 * Y.s35)
  s12 := 2 * (X.h1 * Y.r12 - X.r12 * Y.h1) + (X.r12 * Y.h2 - X.h2 * Y.r12) + (X.r13 * Y.s23 - X.s23 * Y.r13) + (X.r14 * Y.s24 - X.s24 * Y.r14) + (X.r15 * Y.s25 - X.s25 * Y.r15) + (X.r23 * Y.s13 - X.s13 * Y.r23) + (X.r24 * Y.s14 - X.s14 * Y.r24) + (X.r25 * Y.s15 - X.s15 * Y.r25)
  s13 := (X.h1 * Y.r13 - X.r13 * Y.h1) + (X.h2 * Y.r13 - X.r13 * Y.h2) + (X.r13 * Y.h3 - X.h3 * Y.r13) + (X.r12 * Y.s23 - X.s23 * Y.r12) + (X.r14 * Y.s34 - X.s34 * Y.r14) + (X.r15 * Y.s35 - X.s35 * Y.r15) + (X.s12 * Y.r23 - X.r23 * Y.s12) + (X.r34 * Y.s14 - X.s14 * Y.r34) + (X.r35 * Y.s15 - X.s15 * Y.r35)
  s14 := (X.h1 * Y.r14 - X.r14 * Y.h1) + (X.h3 * Y.r14 - X.r14 * Y.h3) + (X.r14 * Y.h4 - X.h4 * Y.r14) + (X.r12 * Y.s24 - X.s24 * Y.r12) + (X.r13 * Y.s34 - X.s34 * Y.r13) + (X.r15 * Y.s45 - X.s45 * Y.r15) + (X.s12 * Y.r24 - X.r24 * Y.s12) + (X.s13 * Y.r34 - X.r34 * Y.s13) + (X.r45 * Y.s15 - X.s15 * Y.r45)
  s15 := (X.h1 * Y.r15 - X.r15 * Y.h1) + (X.h4 * Y.r15 - X.r15 * Y.h4) + (X.r12 * Y.s25 - X.s25 * Y.r12) + (X.r13 * Y.s35 - X.s35 * Y.r13) + (X.r14 * Y.s45 - X.s45 * Y.r14) + (X.s12 * Y.r25 - X.r25 * Y.s12) + (X.s13 * Y.r35 - X.r35 * Y.s13) + (X.s14 * Y.r45 - X.r45 * Y.s14)
  s23 := (X.r23 * Y.h1 - X.h1 * Y.r23) + 2 * (X.h2 * Y.r23 - X.r23 * Y.h2) + (X.r23 * Y.h3 - X.h3 * Y.r23) + (X.s13 * Y.r12 - X.r12 * Y.s13) + (X.s12 * Y.r13 - X.r13 * Y.s12) + (X.r24 * Y.s34 - X.s34 * Y.r24) + (X.r25 * Y.s35 - X.s35 * Y.r25) + (X.r34 * Y.s24 - X.s24 * Y.r34) + (X.r35 * Y.s25 - X.s25 * Y.r35)
  s24 := (X.r24 * Y.h1 - X.h1 * Y.r24) + (X.h2 * Y.r24 - X.r24 * Y.h2) + (X.h3 * Y.r24 - X.r24 * Y.h3) + (X.r24 * Y.h4 - X.h4 * Y.r24) + (X.s14 * Y.r12 - X.r12 * Y.s14) + (X.s12 * Y.r14 - X.r14 * Y.s12) + (X.r23 * Y.s34 - X.s34 * Y.r23) + (X.r25 * Y.s45 - X.s45 * Y.r25) + (X.s23 * Y.r34 - X.r34 * Y.s23) + (X.r45 * Y.s25 - X.s25 * Y.r45)
  s25 := (X.r25 * Y.h1 - X.h1 * Y.r25) + (X.h2 * Y.r25 - X.r25 * Y.h2) + (X.h4 * Y.r25 - X.r25 * Y.h4) + (X.s15 * Y.r12 - X.r12 * Y.s15) + (X.s12 * Y.r15 - X.r15 * Y.s12) + (X.r23 * Y.s35 - X.s35 * Y.r23) + (X.r24 * Y.s45 - X.s45 * Y.r24) + (X.s23 * Y.r35 - X.r35 * Y.s23) + (X.s24 * Y.r45 - X.r45 * Y.s24)
  s34 := (X.r34 * Y.h2 - X.h2 * Y.r34) + 2 * (X.h3 * Y.r34 - X.r34 * Y.h3) + (X.r34 * Y.h4 - X.h4 * Y.r34) + (X.s14 * Y.r13 - X.r13 * Y.s14) + (X.s13 * Y.r14 - X.r14 * Y.s13) + (X.s24 * Y.r23 - X.r23 * Y.s24) + (X.s23 * Y.r24 - X.r24 * Y.s23) + (X.r35 * Y.s45 - X.s45 * Y.r35) + (X.r45 * Y.s35 - X.s35 * Y.r45)
  s35 := (X.r35 * Y.h2 - X.h2 * Y.r35) + (X.h3 * Y.r35 - X.r35 * Y.h3) + (X.h4 * Y.r35 - X.r35 * Y.h4) + (X.s15 * Y.r13 - X.r13 * Y.s15) + (X.s13 * Y.r15 - X.r15 * Y.s13) + (X.s25 * Y.r23 - X.r23 * Y.s25) + (X.s23 * Y.r25 - X.r25 * Y.s23) + (X.r34 * Y.s45 - X.s45 * Y.r34) + (X.s34 * Y.r45 - X.r45 * Y.s34)
  s45 := (X.r45 * Y.h3 - X.h3 * Y.r45) + 2 * (X.h4 * Y.r45 - X.r45 * Y.h4) + (X.s15 * Y.r14 - X.r14 * Y.s15) + (X.s14 * Y.r15 - X.r15 * Y.s14) + (X.s25 * Y.r24 - X.r24 * Y.s25) + (X.s24 * Y.r25 - X.r25 * Y.s24) + (X.s35 * Y.r34 - X.r34 * Y.s35) + (X.s34 * Y.r35 - X.r35 * Y.s34)

/-! ## Part 4: Typeclass Instances -/

instance : Sub SU5C := ⟨fun a b => add a (neg b)⟩
instance : SMul ℝ SU5C := ⟨smul⟩

@[simp] lemma sub_def' (a b : SU5C) : a - b = add a (neg b) := rfl
@[simp] lemma smul_def' (r : ℝ) (a : SU5C) : r • a = smul r a := rfl

instance : AddCommGroup SU5C where
  add_assoc := by intros; ext <;> simp [add] <;> ring
  zero_add := by intros; ext <;> simp [add, zero]
  add_zero := by intros; ext <;> simp [add, zero]
  add_comm := by intros; ext <;> simp [add] <;> ring
  neg_add_cancel := by intros; ext <;> simp [add, neg, zero]
  sub_eq_add_neg := by intros; rfl
  nsmul := nsmulRec
  zsmul := zsmulRec

instance : Module ℝ SU5C where
  one_smul := by intros; ext <;> simp [smul]
  mul_smul := by intros; ext <;> simp [smul] <;> ring
  smul_zero := by intros; ext <;> simp [smul, zero]
  smul_add := by intros; ext <;> simp [smul, add] <;> ring
  add_smul := by intros; ext <;> simp [smul, add] <;> ring
  zero_smul := by intros; ext <;> simp [smul, zero]

instance : Bracket SU5C SU5C := ⟨comm⟩

@[simp] lemma bracket_def' (a b : SU5C) : ⁅a, b⁆ = comm a b := rfl

set_option maxHeartbeats 12000000 in
instance : LieRing SU5C where
  add_lie := by intros; ext <;> simp [comm, add] <;> ring
  lie_add := by intros; ext <;> simp [comm, add] <;> ring
  lie_self := by intro x; ext <;> simp [comm, zero] <;> ring
  leibniz_lie := by intros; ext <;> simp [comm, add] <;> ring

set_option maxHeartbeats 6000000 in
instance : LieAlgebra ℝ SU5C where
  lie_smul := by intros; ext <;> simp [comm, smul] <;> ring

end SU5C

/-! ## Summary

### What this file proves:
1. su(5) compact form as a 24-dimensional Lie algebra (Parts 1-3)
2. Certified LieRing and LieAlgebra ℝ instances (Part 4)

### Compact vs split form:
- su5_grand.lean: sl(5,ℝ), the split real form, Chevalley basis (e/f/h)
- THIS FILE: su(5), the compact real form, rotation basis (R/S/H)

The compact form is what embeds in so(10) via the complex structure J.
The split form CANNOT embed in compact so(10) — different real forms.

### Machine verification:
- Structure constants generated by scripts/su5c_bracket_gen.py
- 276 bracket pairs verified to close in 24-dim su(5)
- Jacobi identity verified numerically for 1000 random triples
- LieRing and LieAlgebra instances accepted by Lean 4 kernel

0 sorry gaps.
-/
