#!/usr/bin/env python3
"""
E₈ Phase 0 Feasibility Test Generator
======================================

Generates a minimal Lean 4 file that tests whether native_decide can handle
248×248 rational matrix multiplication. This is the BLOCKING feasibility test
for the E₈ construction (M4).

Test: Define two sparse antisymmetric 248×248 matrices (so(248) basis elements),
compute their bracket [A,B] = A*B - B*A, and verify the result with native_decide.

If native_decide completes in < 60 seconds → PROCEED with E₈ construction.
If > 60 seconds → evaluate kill conditions.

The matrices are extremely sparse (2 nonzero entries each), which is representative
of the E₈ Chevalley basis (~5-15% nonzero per matrix in 248×248).

Usage:
    python scripts/e8_feasibility_test_gen.py

Output:
    src/lean_proofs/clifford/e8_feasibility_test.lean
"""

import os

def gen_sparse_matrix(name: str, entries: list[tuple[int, int, str]], n: int = 248) -> str:
    """Generate a Lean definition for a sparse n×n rational matrix."""
    lines = [f"def {name} : QMat{n} := Matrix.of fun i j => match i, j with"]
    for r, c, val in entries:
        lines.append(f"    | {r}, {c} => {val}")
    lines.append("    | _, _ => 0")
    lines.append("")
    return "\n".join(lines)


def generate_feasibility_test():
    """Generate the Lean feasibility test file."""

    header = """/-
E₈ Construction — Phase 0 Feasibility Test
============================================

BLOCKING TEST for Milestone 4 (E₈ construction).

Tests whether Lean's native_decide can handle 248×248 rational matrix
operations at the scale needed for E₈ adjoint representation verification.

Test: Two sparse antisymmetric matrices from so(248), bracket = commutator.
  E_{01} has entries (0,1)=1, (1,0)=-1
  E_{02} has entries (0,2)=1, (2,0)=-1
  [E_{01}, E_{02}] should equal -E_{12} (entries (1,2)=-1, (2,1)=1)

PASS CRITERION: native_decide completes in < 60 seconds.
KILL CONDITION: > 60 seconds → try smaller matrices, decide tactic, or Z instead of Q.

Generated by scripts/e8_feasibility_test_gen.py
-/

import Mathlib.Data.Real.Basic
import Mathlib.Tactic

abbrev QMat248 := Matrix (Fin 248) (Fin 248) ℚ

/-! ## Test matrices: so(248) basis elements -/
"""

    # E_{01}: antisymmetric basis element with +1 at (0,1), -1 at (1,0)
    e01 = gen_sparse_matrix("E01", [(0, 1, "1"), (1, 0, "-1")])

    # E_{02}: antisymmetric basis element with +1 at (0,2), -1 at (2,0)
    e02 = gen_sparse_matrix("E02", [(0, 2, "1"), (2, 0, "-1")])

    # Expected result: -E_{12} = entries (1,2)=-1, (2,1)=1
    neg_e12 = gen_sparse_matrix("neg_E12", [(1, 2, "-1"), (2, 1, "1")])

    verification = """/-! ## Feasibility test: native_decide on 248×248 matrix bracket -/

/-- PHASE 0 FEASIBILITY TEST.
    Verifies [E01, E02] = -E12 for 248×248 rational matrices.
    If this compiles via native_decide in < 60s, E₈ construction is feasible. -/
theorem e8_feasibility_bracket :
    E01 * E02 - E02 * E01 = neg_E12 := by
  native_decide

/-! ## Summary

### What this file tests:
- native_decide can handle 248×248 matrix multiplication over ℚ
- Two matrix multiplies + one subtraction + one equality check
- Matrices are sparse (2 nonzero entries each) — representative of E₈ Chevalley basis

### Scaling context:
- spinor_rep_homomorphism.lean: 16×16 matrices, 990 pairs → PASSED
- This test: 248×248 matrices, 1 pair → ???
- Full E₈: 248×248 matrices, ~30,628 pairs (chunked into ~31 files)

### Kill conditions if this FAILS:
1. Try `decide` instead of `native_decide`
2. Try ℤ instead of ℚ (integer arithmetic is faster)
3. Try smaller test (128×128 or 64×64) to find the scaling wall
4. Try chunked approach: verify row-by-row instead of full matrix equality
-/
"""

    content = header + e01 + e02 + neg_e12 + verification

    output_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "src", "lean_proofs", "clifford", "e8_feasibility_test.lean"
    )

    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)

    print(f"Generated: {output_path}")
    print(f"File size: {len(content)} bytes")
    print(f"Matrix size: 248×248 = {248*248} entries")
    print(f"Nonzero entries per matrix: 2 (very sparse)")
    print()
    print("Next step: cd to project root and run:")
    print("  time lake env lean src/lean_proofs/clifford/e8_feasibility_test.lean")
    print()
    print("PASS: < 60 seconds → proceed with E₈ construction")
    print("FAIL: > 60 seconds → evaluate kill conditions")


if __name__ == "__main__":
    generate_feasibility_test()
