#!/usr/bin/env python3
"""
E₈ Full Lean Code Generator
=============================

Generates ~31 Lean 4 files containing:
- 248 adjoint matrices (248×248 over ℤ)
- All 30,628 bracket equations verified by native_decide

Each file contains a chunk of matrix definitions and bracket theorems.
Designed for parallel compilation via `lake build -j16`.

Input: research/e8-construction/e8_structure_constants.json (from SageMath oracle)
Output: src/lean_proofs/clifford/e8_chunk_XX.lean (XX = 00..30)

Convention: ad(B_i)_{k,j} = f^k_{ij} where [B_i, B_j] = Σ_k f^k_{ij} B_k
Verified by e8_bracket_test.lean (5 theorems, all passed native_decide).
"""

import json
import os
import sys
import math


def main():
    # ── Load structure constants ──
    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    json_path = os.path.join(base_dir, 'research', 'e8-construction',
                              'e8_structure_constants.json')
    out_dir = os.path.join(base_dir, 'src', 'lean_proofs', 'clifford')

    print(f"Loading {json_path}...")
    with open(json_path) as f:
        data = json.load(f)

    sc = {}
    for key_str, terms in data['structure_constants'].items():
        i, j = map(int, key_str.split(','))
        sc[(i, j)] = [(k, c) for k, c in terms]

    n = 248

    def get_bracket(i, j):
        if i == j:
            return []
        if i < j:
            return sc.get((i, j), [])
        else:
            return [(_k, -_c) for _k, _c in sc.get((j, i), [])]

    # ── Build all adjoint matrices ──
    print("Building adjoint matrices...")
    ads = {}  # idx -> dict of (row, col) -> value
    for idx in range(n):
        entries = {}
        for j in range(n):
            terms = get_bracket(idx, j)
            for k, c in terms:
                entries[(k, j)] = c
        ads[idx] = entries

    # ── Enumerate ALL bracket pairs ──
    print("Enumerating bracket pairs...")
    all_pairs = []
    for i in range(n):
        for j in range(i + 1, n):
            terms = sc.get((i, j), [])
            all_pairs.append((i, j, terms))

    total_pairs = len(all_pairs)
    print(f"  Total pairs: {total_pairs}")

    # ── Chunking strategy ──
    # Goal: ~31 files, each with ~1000 bracket checks
    # Each file needs all 248 matrix definitions (imported from a shared file)
    # Actually, better: put matrix defs in separate files, bracket checks in others

    # Strategy:
    # - e8_defs_XX.lean (8 files): matrix definitions, ~31 matrices each
    # - e8_bracket_XX.lean (31 files): bracket theorems, ~1000 each
    # - e8_defs.lean: imports all def files (shared)

    # Simpler approach: each chunk file defines the matrices it needs locally
    # BUT that duplicates matrices across files (bad for compile time)

    # Best approach: ONE definitions file with all 248 matrices,
    # then 31 bracket files that import it.
    # The defs file has no native_decide so it compiles fast.

    # ── Generate definitions file ──
    print("\nGenerating definitions file...")
    defs_lines = []
    defs_lines.append("/-")
    defs_lines.append("E₈ Adjoint Matrices — All 248 Basis Elements")
    defs_lines.append("==============================================")
    defs_lines.append("")
    defs_lines.append("248 matrices of type Matrix (Fin 248) (Fin 248) ℤ,")
    defs_lines.append("representing the adjoint action of each Chevalley basis element.")
    defs_lines.append("")
    defs_lines.append("Convention: ad(B_i)_{k,j} = f^k_{ij}")
    defs_lines.append("  where [B_i, B_j] = Σ_k f^k_{ij} B_k")
    defs_lines.append("")
    defs_lines.append("Basis ordering:")
    defs_lines.append("  0-7:     H_1..H_8 (Cartan coroots)")
    defs_lines.append("  8-127:   E_1..E_120 (positive root vectors, by height)")
    defs_lines.append("  128-247: F_1..F_120 (negative root vectors, same order)")
    defs_lines.append("")
    defs_lines.append("Generated by scripts/e8_lean_gen.py from SageMath oracle output.")
    defs_lines.append("Structure constants verified: Jacobi 0/2,511,496 failures.")
    defs_lines.append("-/")
    defs_lines.append("")
    defs_lines.append("import Mathlib.Data.Real.Basic")
    defs_lines.append("import Mathlib.Tactic")
    defs_lines.append("")
    defs_lines.append("namespace E8")
    defs_lines.append("")
    defs_lines.append("abbrev Mat := Matrix (Fin 248) (Fin 248) ℤ")
    defs_lines.append("")

    for idx in range(n):
        entries = ads[idx]
        defs_lines.append(f"def ad{idx} : Mat := Matrix.of fun i j => match i.val, j.val with")
        for (row, col), val in sorted(entries.items()):
            defs_lines.append(f"  | {row}, {col} => {val}")
        defs_lines.append(f"  | _, _ => 0")
        defs_lines.append("")

    defs_lines.append("end E8")

    defs_path = os.path.join(out_dir, 'e8_defs.lean')
    with open(defs_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(defs_lines))
    print(f"  Written: {defs_path} ({len(defs_lines)} lines)")

    # ── Generate bracket chunk files ──
    n_chunks = 31
    chunk_size = math.ceil(total_pairs / n_chunks)
    print(f"\nGenerating {n_chunks} bracket files (~{chunk_size} pairs each)...")

    for chunk_idx in range(n_chunks):
        start = chunk_idx * chunk_size
        end = min(start + chunk_size, total_pairs)
        chunk_pairs = all_pairs[start:end]

        if not chunk_pairs:
            break

        chunk_name = f"e8_chunk_{chunk_idx:02d}"
        lines = []
        lines.append(f"/-")
        lines.append(f"E₈ Bracket Verification — Chunk {chunk_idx:02d}")
        lines.append(f"Pairs {start}..{end-1} of {total_pairs}")
        lines.append(f"-/")
        lines.append(f"")
        lines.append(f"import clifford.e8_defs")
        lines.append(f"")
        lines.append(f"set_option maxHeartbeats 800000")
        lines.append(f"")
        lines.append(f"open E8")
        lines.append(f"")

        for pair_idx, (i, j, terms) in enumerate(chunk_pairs):
            global_idx = start + pair_idx
            theorem_name = f"e8_bracket_{global_idx}"

            if not terms:
                # Zero bracket
                lines.append(f"theorem {theorem_name} :")
                lines.append(f"    ad{i} * ad{j} - ad{j} * ad{i} = (0 : Mat) := by")
            elif len(terms) == 1:
                k, c = terms[0]
                if c == 1:
                    rhs = f"ad{k}"
                elif c == -1:
                    rhs = f"-(ad{k})"
                else:
                    rhs = f"({c} : ℤ) • ad{k}"
                lines.append(f"theorem {theorem_name} :")
                lines.append(f"    ad{i} * ad{j} - ad{j} * ad{i} = {rhs} := by")
            else:
                # Multiple terms
                parts = []
                for k, c in sorted(terms):
                    if c == 1:
                        parts.append(f"ad{k}")
                    elif c == -1:
                        parts.append(f"-(ad{k})")
                    else:
                        parts.append(f"({c} : ℤ) • ad{k}")
                rhs = " + ".join(parts)
                lines.append(f"theorem {theorem_name} :")
                lines.append(f"    ad{i} * ad{j} - ad{j} * ad{i} = {rhs} := by")

            lines.append(f"  native_decide")
            lines.append(f"")

        chunk_path = os.path.join(out_dir, f'{chunk_name}.lean')
        with open(chunk_path, 'w', encoding='utf-8') as f:
            f.write('\n'.join(lines))
        print(f"  {chunk_name}.lean: {len(chunk_pairs)} theorems, {len(lines)} lines")

    # ── Generate root file that imports everything ──
    root_lines = []
    root_lines.append("/-")
    root_lines.append("E₈ as a Certified Lie Algebra — All Bracket Relations Verified")
    root_lines.append("===============================================================")
    root_lines.append("")
    root_lines.append("This file imports the complete E₈ verification:")
    root_lines.append(f"  - e8_defs.lean: 248 adjoint matrices (248×248 over ℤ)")
    root_lines.append(f"  - e8_chunk_00..e8_chunk_{n_chunks-1:02d}: {total_pairs} bracket theorems")
    root_lines.append("")
    root_lines.append("Every bracket relation [B_i, B_j] = Σ_k f^k_{ij} B_k is verified")
    root_lines.append("by Lean's native_decide kernel — not by trust, by computation.")
    root_lines.append("")
    root_lines.append("Structure constants from SageMath Chevalley basis (GAP + Chevie).")
    root_lines.append("Cross-verified: SageMath oracle ↔ Python Jacobi (0/2,511,496) ↔ Lean kernel.")
    root_lines.append("-/")
    root_lines.append("")
    root_lines.append("import clifford.e8_defs")
    for chunk_idx in range(n_chunks):
        root_lines.append(f"import clifford.e8_chunk_{chunk_idx:02d}")
    root_lines.append("")

    root_path = os.path.join(out_dir, 'e8_root.lean')
    with open(root_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(root_lines))
    print(f"\n  e8_root.lean: imports all chunks")

    # ── Summary ──
    print(f"\n{'='*60}")
    print(f"GENERATION COMPLETE")
    print(f"{'='*60}")
    print(f"  Definitions: e8_defs.lean ({len(defs_lines)} lines, 248 matrices)")
    print(f"  Chunks: e8_chunk_00..e8_chunk_{n_chunks-1:02d} ({total_pairs} theorems)")
    print(f"  Root: e8_root.lean (imports all)")
    print(f"")
    print(f"  Estimated compilation time: ~26 hours (i7-11800H, 64GB, -j16)")
    print(f"  Command: lake build 2>&1 | tee e8_build.log")
    print(f"")
    print(f"  IMPORTANT: Set 'Put the computer to sleep' to NEVER before starting!")

    return 0


if __name__ == '__main__':
    sys.exit(main())
