#!/usr/bin/env python3
"""
Generate the SO14 → SO14M type bridge (flat Lie algebra → matrix LieSubalgebra).

This script generates a Lean 4 file that constructs a certified LieHom
from SO14 (91-field flat type in so14_grand.lean) to SO14M (mathlib
LieSubalgebra of 14×14 antisymmetric matrices, defined in so16_matrix.lean).

The map: each flat field l_{ij} maps to the antisymmetric basis matrix
  E_{i-1,j-1} - E_{j-1,i-1}
(converting from 1-indexed field names to 0-indexed Fin 14).

Proof structure:
1. Define so14_to_mat : SO14 → Matrix (Fin 14) (Fin 14) ℝ (entry-by-entry)
2. Prove skew-symmetry → output ∈ SO14M
3. Prove linearity (map_add', map_smul')
4. Prove bracket preservation (map_lie') via fin_cases + ring
5. Package as SO14 →ₗ⁅ℝ⁆ SO14M

References:
  - so14_grand.lean: source type (SO14, 91 fields)
  - so16_matrix.lean: target type (SO14M = so(Fin 14) ℝ)
  - su5c_so10_liehom.lean: LieHom pattern
  - so14_bracket_gen.py: field naming conventions
"""

import itertools
import os
from collections import defaultdict

# ============================================================
# Configuration (mirrors so14_bracket_gen.py)
# ============================================================
N = 14
pairs = [(i, j) for i in range(1, N+1) for j in range(i+1, N+1)]
assert len(pairs) == 91, f"Expected 91 pairs, got {len(pairs)}"

def idx_char(k):
    """Convert 1-based index to field name character."""
    return str(k) if k <= 9 else chr(ord('a') + k - 10)

def field_name(i, j):
    """Generate Lean field name for L_{ij}."""
    return f"l{idx_char(i)}{idx_char(j)}"

pair_to_field = {(i,j): field_name(i,j) for i,j in pairs}
fields = [pair_to_field[p] for p in pairs]

# ============================================================
# Bracket computation (for map_lie' verification)
# ============================================================
def canonical(p, q):
    if p == q:
        return None, 0
    if p < q:
        return (p, q), 1
    else:
        return (q, p), -1

def compute_bracket(ij, kl):
    i, j = ij
    k, l = kl
    result = defaultdict(int)
    terms = []
    if j == k: terms.append((i, l, +1))
    if i == k: terms.append((j, l, -1))
    if j == l: terms.append((i, k, -1))
    if i == l: terms.append((j, k, +1))
    for p, q, coeff in terms:
        can, sign = canonical(p, q)
        if can is not None:
            result[can] += coeff * sign
    return {k: v for k, v in result.items() if v != 0}

brackets = {}
for ij in pairs:
    for kl in pairs:
        b = compute_bracket(ij, kl)
        if b:
            brackets[(ij, kl)] = b

print(f"Non-zero brackets: {len(brackets)} / {len(pairs)**2}")

# ============================================================
# Generate Lean file
# ============================================================

lean = """/-
UFT Formal Verification - SO(14) Type Bridge: Flat → Matrix
=============================================================

CERTIFIED LieHom: SO14 →ₗ⁅ℝ⁆ SO14M

This file constructs a LieHom from the flat 91-field SO14 type
(so14_grand.lean) to the mathlib matrix SO14M type (so16_matrix.lean).

SO14M is `LieAlgebra.Orthogonal.so (Fin 14) ℝ`, the Lie subalgebra of
14×14 antisymmetric real matrices. The bracket is the matrix commutator:
  [A, B] = A * B - B * A

The map sends each generator field l_{ij} to the antisymmetric basis
matrix E_{i-1,j-1} - E_{j-1,i-1}, producing a 14×14 matrix whose
upper-triangular entries are exactly the SO14 fields.

This bridge resolves the type gap between the flat algebraic construction
(SO14 with explicit structure constants) and the matrix formulation
(SO14M with inherited mathlib LieAlgebra instance).

Generated by scripts/so14_bridge_gen.py.

References:
  - so14_grand.lean: SO14 type with 91 generators, LieAlgebra ℝ instance
  - so16_matrix.lean: SO14M = LieAlgebra.Orthogonal.so (Fin 14) ℝ
  - su5c_so10_liehom.lean: LieHom pattern source
-/

import clifford.so14_grand
import clifford.so16_matrix

open Matrix LieAlgebra.Orthogonal

/-! ## Part 1: The Map SO14 → Matrix (Fin 14) (Fin 14) ℝ

Each flat field l_{ij} maps to the antisymmetric matrix with +1 at
position (i-1, j-1) and -1 at position (j-1, i-1).

Defined entry-by-entry for clean simp reduction. -/

/-- Map from flat SO14 (91 generators) to 14×14 real matrix.
    Upper triangle: x.l_{i+1,j+1} for i < j.
    Lower triangle: -x.l_{j+1,i+1} for i > j.
    Diagonal: 0.
    Generated by scripts/so14_bridge_gen.py. -/
def so14_to_mat (x : SO14) : Matrix (Fin 14) (Fin 14) ℝ := fun i j =>
  match i.val, j.val with
"""

# Generate match arms: upper triangle (i < j)
for i, j in pairs:
    fn = field_name(i, j)
    lean += f"  | {i-1}, {j-1} => x.{fn}\n"

# Generate match arms: lower triangle (i > j, antisymmetric)
for i, j in pairs:
    fn = field_name(i, j)
    lean += f"  | {j-1}, {i-1} => -x.{fn}\n"

lean += "  | _, _ => 0\n"

lean += """
/-! ## Part 2: Skew-Symmetry and SO14M Membership -/

set_option maxHeartbeats 4000000 in
/-- The output matrix is skew-symmetric: (so14_to_mat x)ᵀ = -(so14_to_mat x). -/
theorem so14_to_mat_skew (x : SO14) : (so14_to_mat x)ᵀ = -(so14_to_mat x) := by
  ext i j
  simp only [Matrix.transpose_apply, Matrix.neg_apply]
  fin_cases i <;> fin_cases j <;> simp [so14_to_mat]

/-- The output matrix is in SO14M (the so(14) LieSubalgebra of antisymmetric matrices). -/
theorem so14_to_mat_mem (x : SO14) : so14_to_mat x ∈ SO14M := by
  rw [LieAlgebra.Orthogonal.mem_so]
  exact so14_to_mat_skew x

/-- Lift the map to target SO14M (subtype of antisymmetric matrices). -/
def so14_to_SO14M (x : SO14) : SO14M :=
  ⟨so14_to_mat x, so14_to_mat_mem x⟩

/-! ## Part 3: Linearity -/

set_option maxHeartbeats 4000000 in
/-- The map preserves addition. -/
theorem so14_to_SO14M_add (a b : SO14) :
    so14_to_SO14M (a + b) = so14_to_SO14M a + so14_to_SO14M b := by
  apply Subtype.ext
  ext i j
  simp only [so14_to_SO14M, AddMemClass.coe_add, Matrix.add_apply]
  fin_cases i <;> fin_cases j <;> simp [so14_to_mat, SO14.add, SO14.add_def]

set_option maxHeartbeats 4000000 in
/-- The map preserves scalar multiplication. -/
theorem so14_to_SO14M_smul (r : ℝ) (a : SO14) :
    so14_to_SO14M (r • a) = r • so14_to_SO14M a := by
  apply Subtype.ext
  ext i j
  simp only [so14_to_SO14M, SetLike.val_smul, Matrix.smul_apply, smul_eq_mul]
  fin_cases i <;> fin_cases j <;> simp [so14_to_mat, SO14.smul, SO14.smul_def'] <;> ring

/-! ## Part 4: Bracket Preservation

The main theorem: so14_to_SO14M preserves the Lie bracket.

LHS: so14_to_mat (comm x y) — the flat bracket mapped to a matrix.
RHS: so14_to_mat x * so14_to_mat y - so14_to_mat y * so14_to_mat x — the matrix commutator.

Both sides are degree-2 polynomials in the 182 input variables (91 from x, 91 from y).
After fin_cases on matrix indices, each of the 196 goals is verified by ring.

The proof is split into 14 row lemmas for manageable compilation. -/

"""

# Generate the sum_fin14 helper
lean += """-- Helper: expand Finset.sum over Fin 14
-- This lets simp reduce matrix multiplication entries.
@[simp] theorem sum_fin14 {M : Type*} [AddCommMonoid M] (f : Fin 14 → M) :
    ∑ i : Fin 14, f i = f 0 + f 1 + f 2 + f 3 + f 4 + f 5 + f 6 + f 7 +
                         f 8 + f 9 + f 10 + f 11 + f 12 + f 13 := by
  simp only [Fin.sum_univ_succ, Fin.sum_univ_zero]
  abel

"""

# Generate per-row bracket lemmas
# For each row r (0..13), prove:
# ∀ j, so14_to_mat (⁅x, y⁆) r j = (so14_to_mat x * so14_to_mat y - ...) r j
for row in range(14):
    lean += f"""set_option maxHeartbeats 64000000 in
/-- Bracket preservation, row {row}. -/
theorem so14_bridge_lie_row{row} (x y : SO14) (j : Fin 14) :
    so14_to_mat ⁅x, y⁆ {row} j =
    (so14_to_mat x * so14_to_mat y - so14_to_mat y * so14_to_mat x) {row} j := by
  simp only [SO14.bracket_def', Matrix.sub_apply, Matrix.mul_apply, sum_fin14]
  fin_cases j <;> simp [so14_to_mat, SO14.comm] <;> ring

"""

# Main bracket preservation theorem
lean += """set_option maxHeartbeats 4000000 in
/-- THE HOMOMORPHISM THEOREM: the map preserves the Lie bracket.
    so14_to_SO14M([X,Y]_{so14}) = [so14_to_SO14M(X), so14_to_SO14M(Y)]_{so14m}

    This certifies that the flat SO14 bracket (defined by structure constants)
    and the matrix SO14M bracket (defined by the commutator A*B - B*A) are
    algebraically identical under the type bridge.

    182 input variables × 196 output entries × polynomial ring verification.
    Split into 14 row lemmas for compilation. -/
theorem so14_to_SO14M_lie (x y : SO14) :
    so14_to_SO14M ⁅x, y⁆ = ⁅so14_to_SO14M x, so14_to_SO14M y⁆ := by
  apply Subtype.ext
  simp only [LieSubalgebra.coe_bracket, LieRing.of_associative_ring_bracket, so14_to_SO14M]
  ext i j
  fin_cases i
"""

for row in range(14):
    lean += f"  · exact so14_bridge_lie_row{row} x y j\n"

lean += """
/-! ## Part 5: The Certified LieHom -/

/-- The certified Lie algebra homomorphism SO14 →ₗ⁅ℝ⁆ SO14M.
    This bridges the flat 91-field type (with explicit structure constants)
    to the mathlib matrix type (with inherited bracket from matrix commutator).

    Combined with the existing morphism chain:
      SU5C →ₗ⁅ℝ⁆ SO10 →ₗ⁅ℝ⁆ SO14 →ₗ⁅ℝ⁆[bridge] SO14M →ₗ⁅ℝ⁆ SO16M

    This connects the verified algebraic chain to mathlib's matrix infrastructure,
    enabling composition with so14m_embed_block : SO14M →ₗ⁅ℝ⁆ SO16Block. -/
def so14_bridge : SO14 →ₗ⁅ℝ⁆ SO14M :=
  { toLinearMap := {
      toFun := so14_to_SO14M
      map_add' := so14_to_SO14M_add
      map_smul' := so14_to_SO14M_smul
    }
    map_lie' := fun {x} {y} => so14_to_SO14M_lie x y }

/-! ## Summary

### What this file proves:
1. `so14_to_mat` : SO14 → Matrix (Fin 14) (Fin 14) ℝ (entry-by-entry map) [Part 1]
2. Skew-symmetry: output is always antisymmetric [Part 2]
3. SO14M membership: output is in so(14) LieSubalgebra [Part 2]
4. Linearity: preserves addition and scalar multiplication [Part 3]
5. Bracket preservation: flat bracket = matrix commutator [Part 4]
6. `so14_bridge` : SO14 →ₗ⁅ℝ⁆ SO14M — certified LieHom [Part 5]

### What this resolves:
The type gap between flat SO14 (with hand-written bracket) and matrix SO14M
(with mathlib-inherited bracket). This is the bridge that connects the
algebraic chain (SU5C → SO10 → SO14) to the matrix chain (SO14M → SO16M).

### Full certified chain (with bridge):
  SU5C →ₗ⁅ℝ⁆ SO10 →ₗ⁅ℝ⁆ SO14 →[so14_bridge]→ SO14M →[so14m_embed_block]→ SO16Block

0 sorry gaps.
-/
"""

# ============================================================
# Write output
# ============================================================
output_path = "src/lean_proofs/clifford/so14_to_matrix.lean"
os.makedirs(os.path.dirname(output_path), exist_ok=True)
with open(output_path, 'w', encoding='utf-8') as f:
    f.write(lean)

print(f"\nLean file written to: {output_path}")
print(f"Match arms: {len(pairs) * 2} (upper + lower triangle)")
print(f"Row lemmas: 14")
print(f"File size: {len(lean)} bytes ({len(lean)//1024} KB)")
print(f"\nNext: add `clifford.so14_to_matrix` to lakefile.lean roots, then `lake build`.")
